In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import json
from scipy.stats import trim_mean
import math
from pandas.api.types import ( is_numeric_dtype, is_categorical_dtype, is_object_dtype, is_datetime64_any_dtype )

import sys
import os
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

from visualization.initial_eda import eda_per_table_printing_results
application_train_df = pd.read_csv("../data/application_train.csv")

with open("../metadata/schema.json", "r") as f:
    schema = json.load(f)

In [3]:
#Run EDA on previous application
previous_application_df = pd.read_csv("../data/previous_application.csv")
application_train_df.head()

previous_application_with_target_df = pd.merge(previous_application_df, application_train_df[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='inner')
eda_per_table_printing_results(previous_application_with_target_df, schema, "previous_application")

Warning: 'SK_ID_CURR' not found in schema for 'previous_application'. Defaulting to categorical.
Warning: 'TARGET' not found in schema for 'previous_application'. Defaulting to categorical.
--------------------------------------
SK_ID_PREV
basic_data

   cardinality                                               mode
0      1413701  [1000001, 1000003, 1000004, 1000005, 1000007, ...

frequency

    CATEGORY  COUNT SEGMENT
0    2030495      1     top
1    1879375      1     top
2    2488465      1     top
3    2172876      1     top
4    2172884      1     top
5    1074614      1     top
6    2051715      1     top
7    2573091      1     top
8    2032971      1     top
9    2639248      1     top
10   2829206      1     top
11   1175519      1     top
12   2640486      1     top
13   1518293      1     top
14   1602532      1     top
15   2372782      1     top
16   1153202      1     top
17   1447887      1     top
18   2534442      1     top
19   2251906      1     top
20   2012233      1  bottom
21   2564996      1  bottom
22   1195602      1  bottom
23   1396343      1  bottom
24   1370536      1  bottom
25   1479904      1  bottom
26   2780755      1  bottom
27   1937406      1  bottom
28   2368505      1  bottom
29   1098175      1  bottom
30   1920928      1  bottom
31   1714464      1  bottom
32   2731219      1  bottom
33   1173910      1  bottom
34   2462027      1  bottom
35   2605728      1  bottom
36   1444667      1  bottom
37   1325317      1  bottom
38   2833363      1  bottom
39   2418762      1  bottom

--------------------------------------
SK_ID_CURR
basic_data

   cardinality      mode
0       291057  [265681]

frequency

    CATEGORY  COUNT SEGMENT
0     265681     73     top
1     173680     72     top
2     242412     68     top
3     206783     67     top
4     389950     64     top
5     382179     64     top
6     198355     63     top
7     345161     62     top
8     446486     62     top
9     238250     61     top
10    280586     61     top
11    206862     60     top
12    133023     60     top
13    242431     59     top
14    401563     59     top
15    235163     58     top
16    110899     58     top
17    379932     55     top
18    205430     55     top
19    344403     54     top
20    421382      1  bottom
21    235992      1  bottom
22    149407      1  bottom
23    251887      1  bottom
24    257248      1  bottom
25    332065      1  bottom
26    382455      1  bottom
27    289142      1  bottom
28    324320      1  bottom
29    294122      1  bottom
30    364272      1  bottom
31    326859      1  bottom
32    314134      1  bottom
33    295266      1  bottom
34    258315      1  bottom
35    296276      1  bottom
36    220859      1  bottom
37    153745      1  bottom
38    299278      1  bottom
39    191629      1  bottom

--------------------------------------
NAME_CONTRACT_TYPE
basic_data

   cardinality          mode
0            4  [Cash loans]

default_rate

  NAME_CONTRACT_TYPE  TARGET_RATE
0         Cash loans     9.125763
1     Consumer loans     7.709962
2    Revolving loans    10.468618
3                XNA    20.127796

frequency

          CATEGORY   COUNT SEGMENT
0       Cash loans  626764    full
1   Consumer loans  625256    full
2  Revolving loans  161368    full
3              XNA     313    full

--------------------------------------
AMT_ANNUITY
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,307218,21.731469,9.744546,1106483,78.268531,8.352862

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,418058.145,15837.184952,13175.900366,11223.765,14724.906897,13.998458,0.929768

distribution_metrics

      skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  2.69599  34423.11  69364.215        6.18012       2.015048

--------------------------------------
AMT_APPLICATION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,5850000.0,175243.593711,106028.591777,70870.5,293622.193141,246.950606,1.675509

distribution_metrics

      skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  3.40083  450000.0  1350000.0      19.048828            3.0

--------------------------------------
AMT_CREDIT
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,1,0.000071,100.0,1413700,99.999929,8.655231

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,4509688.5,196354.086119,121345.555945,80595.0,319481.250716,268.699431,1.627067

distribution_metrics

       skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  3.257014  533160.0  1515415.5      18.802848       2.842328

--------------------------------------
AMT_DOWN_PAYMENT
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,749540,53.019698,9.545855,664161,46.980302,7.650253

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-0.9,3060045.0,6655.317185,3521.745044,1791.0,20620.30044,25.302201,3.09832

distribution_metrics

        skew      p90      p99  ratio_p99_p50  ratio_p99_p90
0  35.787225  16911.0  64222.2      35.858291       3.797658

--------------------------------------
AMT_GOODS_PRICE
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,319525,22.602021,9.58141,1094176,77.397979,8.384849

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,5850000.0,226451.191283,152721.274782,110245.5,315937.6042,302.035317,1.395169

distribution_metrics

       skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  3.086763  585000.0  1395000.0      12.653578       2.384615

--------------------------------------
WEEKDAY_APPR_PROCESS_START
basic_data

   cardinality         mode
0            7  [WEDNESDAY]

default_rate

  WEEKDAY_APPR_PROCESS_START  TARGET_RATE
0                     FRIDAY     8.750404
1                     MONDAY     8.860700
2                   SATURDAY     8.346926
3                     SUNDAY     8.054798
4                   THURSDAY     8.889837
5                    TUESDAY     8.767402
6                  WEDNESDAY     8.697609

frequency

    CATEGORY   COUNT SEGMENT
0  WEDNESDAY  215519    full
1    TUESDAY  215058    full
2     MONDAY  214509    full
3     FRIDAY  213373    full
4   THURSDAY  211005    full
5   SATURDAY  204159    full
6     SUNDAY  140078    full

--------------------------------------
HOUR_APPR_PROCESS_START
basic_data

   cardinality  mode
0           24  [11]

default_rate

    HOUR_APPR_PROCESS_START  TARGET_RATE
0                         0    15.217391
1                         1     7.777778
2                         2     9.263158
3                         3     9.588714
4                         4     9.896960
5                         5    11.257310
6                         6    11.352223
7                         7    11.038460
8                         8    10.430541
9                         9     9.312324
10                       10     8.728218
11                       11     8.681644
12                       12     8.465162
13                       13     8.658237
14                       14     8.447026
15                       15     8.326234
16                       16     7.863371
17                       17     7.638257
18                       18     7.423816
19                       19     7.066769
20                       20     6.949429
21                       21     7.890123
22                       22     6.796117
23                       23     9.815951

frequency

    CATEGORY   COUNT SEGMENT
0         11  163264    full
1         12  157528    full
2         10  153800    full
3         13  145838    full
4         14  133621    full
5         15  120895    full
6          9  107696    full
7         16  102526    full
8         17   80267    full
9          8   62317    full
10        18   53948    full
11         7   38846    full
12        19   28726    full
13         6   21705    full
14         5   12996    full
15        20   12260    full
16         4    7861    full
17         3    4182    full
18        21    3422    full
19         2     950    full
20        22     618    full
21         1     180    full
22        23     163    full
23         0      92    full

--------------------------------------
FLAG_LAST_APPL_PER_CONTRACT
basic_data

   cardinality mode
0            2  [Y]

default_rate

  FLAG_LAST_APPL_PER_CONTRACT  TARGET_RATE
0                           N    10.814876
1                           Y     8.644065

frequency

  CATEGORY    COUNT SEGMENT
0        Y  1406387    full
1        N     7314    full

--------------------------------------
NFLAG_LAST_APPL_IN_DAY
basic_data

   cardinality mode
0            2  [1]

default_rate

   NFLAG_LAST_APPL_IN_DAY  TARGET_RATE
0                       0    10.011895
1                       1     8.650438

frequency

   CATEGORY    COUNT SEGMENT
0         1  1408657    full
1         0     5044    full

--------------------------------------
RATE_DOWN_PAYMENT
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,749540,53.019698,9.545855,664161,46.980302,7.650253

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-0.000015,1.0,0.080175,0.059443,0.062489,0.107784,0.000132,1.344357

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  2.103429  0.211981  0.521604       8.347091       2.460617

--------------------------------------
RATE_INTEREST_PRIMARY
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,1408910,99.661102,8.657047,4791,0.338898,8.140263

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.034781,1.0,0.189436,0.177074,0.189136,0.090849,0.001313,0.479577

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  5.041113  0.1969  0.696192       3.680899       3.535761

--------------------------------------
RATE_INTEREST_PRIVILEGED
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,1408910,99.661102,8.657047,4791,0.338898,8.140263

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.37315,1.0,0.771284,0.781917,0.835095,0.100644,0.001454,0.130489

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -0.914864  0.867336  0.867336       1.038608            1.0

--------------------------------------
NAME_CASH_LOAN_PURPOSE
basic_data

   cardinality   mode
0           25  [XAP]

default_rate

              NAME_CASH_LOAN_PURPOSE  TARGET_RATE
0       Building a house or an annex    13.822526
1               Business development    12.813370
2                    Buying a garage     6.034483
3       Buying a holiday home / land    11.879050
4                      Buying a home    11.982882
5                   Buying a new car     9.029345
6                  Buying a used car    12.879708
7                        Car repairs    18.379161
8                          Education    10.494753
9                  Everyday expenses    10.526316
10                         Furniture    12.878788
11       Gasification / water supply    17.928287
12                             Hobby    20.000000
13                           Journey    10.652591
14                          Medicine    13.415286
15          Money for a third person    17.391304
16                             Other    12.455331
17           Payments on other loans    16.020343
18  Purchase of electronic equipment    12.526767
19          Refusal to name the goal    23.076923
20                           Repairs    13.003927
21                      Urgent needs    14.953013
22          Wedding / gift / holiday    11.735331
23                               XAP     8.280587
24                               XNA     8.717355

frequency

                            CATEGORY   COUNT SEGMENT
0                                XAP  786937    full
1                                XNA  567351    full
2                            Repairs   20117    full
3                              Other   13432    full
4                       Urgent needs    7236    full
5                  Buying a used car    2469    full
6       Building a house or an annex    2344    full
7                  Everyday expenses    2052    full
8                           Medicine    1871    full
9            Payments on other loans    1573    full
10                         Education    1334    full
11                           Journey    1042    full
12  Purchase of electronic equipment     934    full
13                  Buying a new car     886    full
14          Wedding / gift / holiday     801    full
15                     Buying a home     701    full
16                       Car repairs     691    full
17                         Furniture     660    full
18      Buying a holiday home / land     463    full
19              Business development     359    full
20       Gasification / water supply     251    full
21                   Buying a garage     116    full
22                             Hobby      45    full
23          Money for a third person      23    full
24          Refusal to name the goal      13    full

--------------------------------------
NAME_CONTRACT_STATUS
basic_data

   cardinality        mode
0            4  [Approved]

default_rate

  NAME_CONTRACT_STATUS  TARGET_RATE
0             Approved     7.588655
1             Canceled     9.173569
2              Refused    11.996414
3         Unused offer     8.251724

frequency

       CATEGORY   COUNT SEGMENT
0      Approved  886099    full
1      Canceled  259441    full
2       Refused  245390    full
3  Unused offer   22771    full

--------------------------------------
DAYS_DECISION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2922,-1,-880.367039,-770.202947,-582.0,783.540171,0.658996,0.890015

distribution_metrics

       skew    p90   p99  ratio_p99_p50  ratio_p99_p90
0 -1.034552 -146.0 -13.0       0.022337       0.089041

--------------------------------------
NAME_PAYMENT_TYPE
basic_data

   cardinality                     mode
0            4  [Cash through the bank]

default_rate

                           NAME_PAYMENT_TYPE  TARGET_RATE
0                      Cash through the bank     8.086553
1  Cashless from the account of the employer     8.076514
2                 Non-cash from your account     8.211268
3                                        XNA     9.622342

frequency

                                    CATEGORY   COUNT SEGMENT
0                      Cash through the bank  882700    full
1                                        XNA  522960    full
2                 Non-cash from your account    7100    full
3  Cashless from the account of the employer     941    full

--------------------------------------
CODE_REJECT_REASON
basic_data

   cardinality   mode
0            9  [XAP]

default_rate

  CODE_REJECT_REASON  TARGET_RATE
0             CLIENT     8.251724
1                 HC    11.734163
2              LIMIT    12.559395
3                SCO     9.998162
4              SCOFR    20.928736
5             SYSTEM     6.250000
6              VERIF     9.256252
7                XAP     7.947654
8                XNA    10.095934

frequency

  CATEGORY    COUNT SEGMENT
0      XAP  1145533    full
1       HC   145984    full
2    LIMIT    47773    full
3      SCO    32636    full
4   CLIENT    22771    full
5    SCOFR    10875    full
6      XNA     4378    full
7    VERIF     3079    full
8   SYSTEM      672    full

--------------------------------------
NAME_TYPE_SUITE
basic_data

   cardinality             mode
0            8  [Unaccompanied]

default_rate

   NAME_TYPE_SUITE  TARGET_RATE
0         Children     6.356526
1           Family     7.474159
2  Group of people     8.864697
3          Other_A     8.708440
4          Other_B     8.492006
5  Spouse, partner     8.224221
6    Unaccompanied     8.284401
7              NaN     9.320658

frequency

          CATEGORY   COUNT SEGMENT
0              NaN  694672    full
1    Unaccompanied  427635    full
2           Family  181880    full
3  Spouse, partner   57586    full
4         Children   27106    full
5          Other_B   15073    full
6          Other_A    7820    full
7  Group of people    1929    full

--------------------------------------
NAME_CLIENT_TYPE
basic_data

   cardinality        mode
0            4  [Repeater]

default_rate

  NAME_CLIENT_TYPE  TARGET_RATE
0              New     8.994760
1        Refreshed     7.336257
2         Repeater     8.714616
3              XNA     9.915749

frequency

    CATEGORY    COUNT SEGMENT
0   Repeater  1037682    full
1        New   259540    full
2  Refreshed   114936    full
3        XNA     1543    full

--------------------------------------
NAME_GOODS_CATEGORY
basic_data

   cardinality   mode
0           27  [XNA]

default_rate

         NAME_GOODS_CATEGORY  TARGET_RATE
0         Additional Service     6.422018
1                    Animals     0.000000
2                Audio/Video     7.661809
3           Auto Accessories     9.071933
4   Clothing and Accessories     5.701889
5                  Computers     8.104712
6     Construction Materials     6.967597
7       Consumer Electronics     7.066851
8               Direct Sales     8.181818
9                  Education     5.617978
10                   Fitness     4.216867
11                 Furniture     5.849601
12                 Gardening     6.718346
13                 Homewares     6.637271
14                 Insurance    10.344828
15                   Jewelry     9.040093
16          Medical Supplies     5.617284
17                  Medicine     6.144393
18                    Mobile     8.647022
19         Office Appliances     8.261965
20                     Other     5.733847
21  Photo / Cinema Equipment     7.628875
22         Sport and Leisure     7.244094
23                   Tourism     4.229607
24                  Vehicles    10.056062
25                    Weapon     7.692308
26                       XNA     9.385745

frequency

                    CATEGORY   COUNT SEGMENT
0                        XNA  797209    full
1                     Mobile  193743    full
2       Consumer Electronics  104785    full
3                  Computers   89923    full
4                Audio/Video   85502    full
5                  Furniture   45439    full
6   Photo / Cinema Equipment   21707    full
7     Construction Materials   21356    full
8   Clothing and Accessories   19590    full
9           Auto Accessories    6228    full
10                   Jewelry    5188    full
11                 Homewares    4309    full
12          Medical Supplies    3240    full
13                  Vehicles    2854    full
14         Sport and Leisure    2540    full
15                     Other    2337    full
16                 Gardening    2322    full
17         Office Appliances    1985    full
18                   Tourism    1324    full
19                  Medicine    1302    full
20              Direct Sales     330    full
21                   Fitness     166    full
22        Additional Service     109    full
23                 Education      89    full
24                    Weapon      65    full
25                 Insurance      58    full
26                   Animals       1    full

--------------------------------------
NAME_PORTFOLIO
basic_data

   cardinality   mode
0            5  [POS]

default_rate

  NAME_PORTFOLIO  TARGET_RATE
0          Cards    10.161905
1           Cars     5.526316
2           Cash     8.876509
3            POS     7.635959
4            XNA     9.744705

frequency

  CATEGORY   COUNT SEGMENT
0      POS  592460    full
1     Cash  391663    full
2      XNA  307213    full
3    Cards  121985    full
4     Cars     380    full

--------------------------------------
NAME_PRODUCT_TYPE
basic_data

   cardinality   mode
0            3  [XNA]

default_rate

  NAME_PRODUCT_TYPE  TARGET_RATE
0               XNA     8.354841
1           walk-in    12.469007
2            x-sell     8.087827

frequency

  CATEGORY   COUNT SEGMENT
0      XNA  900053    full
1   x-sell  385394    full
2  walk-in  128254    full

--------------------------------------
CHANNEL_TYPE
basic_data

   cardinality                       mode
0            8  [Credit and cash offices]

default_rate

                 CHANNEL_TYPE  TARGET_RATE
0             AP+ (Cash loan)    12.826455
1                  Car dealer     5.172414
2  Channel of corporate sales     6.375093
3              Contact center    10.269821
4                Country-wide     8.256000
5     Credit and cash offices     9.011030
6            Regional / Local     7.605545
7                       Stone     7.369706

frequency

                     CATEGORY   COUNT SEGMENT
0     Credit and cash offices  600342    full
1                Country-wide  423062    full
2                       Stone  183508    full
3            Regional / Local   92472    full
4              Contact center   58891    full
5             AP+ (Cash loan)   49624    full
6  Channel of corporate sales    5396    full
7                  Car dealer     406    full

--------------------------------------
SELLERPLACE_AREA
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-1,4000000,314.987811,61.016434,4.0,7695.081664,6.47194,24.429776

distribution_metrics

         skew    p90     p99  ratio_p99_p50  ratio_p99_p90
0  497.024023  939.0  3570.0          892.5       3.801917

--------------------------------------
NAME_SELLER_INDUSTRY
basic_data

   cardinality   mode
0           11  [XNA]

default_rate

    NAME_SELLER_INDUSTRY  TARGET_RATE
0        Auto technology    10.367647
1               Clothing     5.724769
2           Connectivity     9.207048
3           Construction     6.574340
4   Consumer electronics     7.553387
5              Furniture     6.116489
6               Industry     7.213135
7                Jewelry     8.875178
8           MLM partners     6.188925
9                Tourism     4.278075
10                   XNA     9.355507

frequency

                CATEGORY   COUNT SEGMENT
0                    XNA  715322    full
1   Consumer electronics  341701    full
2           Connectivity  238350    full
3              Furniture   48966    full
4           Construction   25417    full
5               Clothing   19896    full
6               Industry   16567    full
7        Auto technology    4080    full
8                Jewelry    2107    full
9           MLM partners     921    full
10               Tourism     374    full

--------------------------------------
CNT_PAYMENT
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,307213,21.731116,9.744705,1106488,78.268884,8.352824

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,84.0,16.051936,13.686222,12.0,14.566746,0.013848,0.907476

distribution_metrics

       skew   p90   p99  ratio_p99_p50  ratio_p99_p90
0  1.537309  36.0  60.0            5.0       1.666667

--------------------------------------
NAME_YIELD_GROUP
basic_data

   cardinality   mode
0            5  [XNA]

default_rate

  NAME_YIELD_GROUP  TARGET_RATE
0              XNA     9.863280
1             high     9.545156
2       low_action     6.451449
3       low_normal     7.132099
4           middle     8.043179

frequency

     CATEGORY   COUNT SEGMENT
0         XNA  429198    full
1      middle  324971    full
2        high  306061    full
3  low_normal  274884    full
4  low_action   78587    full

--------------------------------------
PRODUCT_COMBINATION
basic_data

   cardinality    mode
0           18  [Cash]

default_rate

               PRODUCT_COMBINATION  TARGET_RATE
0                      Card Street    11.290357
1                      Card X-Sell     9.304520
2                             Cash     9.541006
3                Cash Street: high    11.363856
4                 Cash Street: low    10.100374
5              Cash Street: middle    11.615554
6                Cash X-Sell: high    11.493642
7                 Cash X-Sell: low     6.583242
8              Cash X-Sell: middle     7.835983
9      POS household with interest     7.734563
10  POS household without interest     6.640194
11      POS industry with interest     6.302390
12   POS industry without interest     4.641747
13        POS mobile with interest     8.810584
14     POS mobile without interest     7.883358
15         POS other with interest     8.134325
16     POS others without interest     7.207637
17                             NaN    20.127796

frequency

                          CATEGORY   COUNT SEGMENT
0                             Cash  235101    full
1      POS household with interest  226464    full
2         POS mobile with interest  190850    full
3              Cash X-Sell: middle  120036    full
4                 Cash X-Sell: low  110599    full
5                      Card Street   94594    full
6       POS industry with interest   83508    full
7   POS household without interest   71519    full
8                      Card X-Sell   66774    full
9                Cash Street: high   51699    full
10               Cash X-Sell: high   50802    full
11             Cash Street: middle   29934    full
12                Cash Street: low   28593    full
13         POS other with interest   20309    full
14     POS mobile without interest   19890    full
15   POS industry without interest   10621    full
16     POS others without interest    2095    full
17                             NaN     313    full

--------------------------------------
DAYS_FIRST_DRAWING
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,561106,39.690571,10.275777,852595,60.309429,7.588832

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2922.0,365243.0,342257.65671,365243.0,365243.0,88832.266598,96.205379,0.259548

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -3.606018  365243.0  365243.0            1.0            1.0

--------------------------------------
DAYS_FIRST_DUE
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,561106,39.690571,10.275777,852595,60.309429,7.588832

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2892.0,365243.0,13488.741567,-990.736055,-825.0,71650.147146,77.597137,5.311848

distribution_metrics

       skew    p90       p99  ratio_p99_p50  ratio_p99_p90
0  4.705048 -173.0  365243.0    -442.718788   -2111.231214

--------------------------------------
DAYS_LAST_DUE_1ST_VERSION
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,561106,39.690571,10.275777,852595,60.309429,7.588832

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2801.0,365243.0,33274.831806,-484.542248,-358.0,106161.775933,114.973244,3.190453

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  2.806976  1374.0  365243.0   -1020.231844       265.8246

--------------------------------------
DAYS_LAST_DUE
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,561106,39.690571,10.275777,852595,60.309429,7.588832

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2889.0,365243.0,76665.634755,50472.193059,-534.0,149704.716371,162.130265,1.952696

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  1.408831  365243.0  365243.0    -683.975655            1.0

--------------------------------------
DAYS_TERMINATION
missings_metrics

,nulls_amount,nulls_porcentaje,default_ratio_nulls,non_null_amount,non_null_porcentaje,non_null_default_ratio
0,561106,39.690571,10.275777,852595,60.309429,7.588832

basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2874.0,365243.0,82353.171672,57578.652969,-494.0,153537.064274,166.280699,1.864373

distribution_metrics

     skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  1.2997  365243.0  365243.0      -739.3583            1.0

--------------------------------------
NFLAG_INSURED_ON_APPROVAL
basic_data

   cardinality   mode
0            3  [0.0]

default_rate

   NFLAG_INSURED_ON_APPROVAL  TARGET_RATE
0                        0.0     7.576684
1                        1.0     7.613432
2                        NaN    10.275777

frequency

   CATEGORY   COUNT SEGMENT
0       0.0  570751    full
1       NaN  561106    full
2       1.0  281844    full

--------------------------------------
TARGET
basic_data

   cardinality mode
0            2  [0]

default_rate

   TARGET  TARGET_RATE
0       0          0.0
1       1        100.0

frequency

   CATEGORY    COUNT SEGMENT
0         0  1291341    full
1         1   122360    full