In [10]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import json
from scipy.stats import trim_mean
import math
from pandas.api.types import ( is_numeric_dtype, is_categorical_dtype, is_object_dtype, is_datetime64_any_dtype )

In [11]:
df = pd.read_csv("../data/application_train.csv")
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
feature_cols = [c for c in df.columns if c not in ["SK_ID_CURR", "TARGET"]]
X = df[feature_cols]
y = df["target"]

KeyError: 'target'

In [12]:
def create_files_nulls_per_colmun(data_frame,table_name):
    nulls=data_frame.isna().sum()
    nulls.head()
    nulls.to_csv("dumps_from_notebooks/" + "null_count_" + table_name,index=True)
    porcentaje_of_nulls = (nulls * 100) / len(data_frame)
    porcentaje_of_nulls.head()
    porcentaje_of_nulls.to_csv("dumps_from_notebooks/null_porcentaje_" + table_name,index=False)

In [13]:
with open("../metadata/schema.json", "r") as f:
    schema = json.load(f)
print(schema)

{'application': {'SK_ID_CURR': {'type': 'categorical'}, 'TARGET': {'type': 'categorical'}, 'NAME_CONTRACT_TYPE': {'type': 'categorical'}, 'CODE_GENDER': {'type': 'categorical'}, 'FLAG_OWN_CAR': {'type': 'categorical'}, 'FLAG_OWN_REALTY': {'type': 'categorical'}, 'CNT_CHILDREN': {'type': 'numerical'}, 'AMT_INCOME_TOTAL': {'type': 'numerical'}, 'AMT_CREDIT': {'type': 'numerical'}, 'AMT_ANNUITY': {'type': 'numerical'}, 'AMT_GOODS_PRICE': {'type': 'numerical'}, 'NAME_TYPE_SUITE': {'type': 'categorical'}, 'NAME_INCOME_TYPE': {'type': 'categorical'}, 'NAME_EDUCATION_TYPE': {'type': 'categorical'}, 'NAME_FAMILY_STATUS': {'type': 'categorical'}, 'NAME_HOUSING_TYPE': {'type': 'categorical'}, 'REGION_POPULATION_RELATIVE': {'type': 'numerical'}, 'DAYS_BIRTH': {'type': 'numerical'}, 'DAYS_EMPLOYED': {'type': 'numerical'}, 'DAYS_REGISTRATION': {'type': 'numerical'}, 'DAYS_ID_PUBLISH': {'type': 'numerical'}, 'OWN_CAR_AGE': {'type': 'numerical'}, 'FLAG_MOBIL': {'type': 'categorical'}, 'FLAG_EMP_PHONE': {'type': 'categorical'}, 'FLAG_WORK_PHONE': {'type': 'categorical'}, 'FLAG_CONT_MOBILE': {'type': 'categorical'}, 'FLAG_PHONE': {'type': 'categorical'}, 'FLAG_EMAIL': {'type': 'categorical'}, 'OCCUPATION_TYPE': {'type': 'categorical'}, 'CNT_FAM_MEMBERS': {'type': 'numerical'}, 'REGION_RATING_CLIENT': {'type': 'categorical'}, 'REGION_RATING_CLIENT_W_CITY': {'type': 'categorical'}, 'WEEKDAY_APPR_PROCESS_START': {'type': 'categorical'}, 'HOUR_APPR_PROCESS_START': {'type': 'categorical'}, 'REG_REGION_NOT_LIVE_REGION': {'type': 'categorical'}, 'REG_REGION_NOT_WORK_REGION': {'type': 'categorical'}, 'LIVE_REGION_NOT_WORK_REGION': {'type': 'categorical'}, 'REG_CITY_NOT_LIVE_CITY': {'type': 'categorical'}, 'REG_CITY_NOT_WORK_CITY': {'type': 'categorical'}, 'LIVE_CITY_NOT_WORK_CITY': {'type': 'categorical'}, 'ORGANIZATION_TYPE': {'type': 'categorical'}, 'EXT_SOURCE_1': {'type': 'numerical'}, 'EXT_SOURCE_2': {'type': 'numerical'}, 'EXT_SOURCE_3': {'type': 'numerical'}, 'APARTMENTS_AVG': {'type': 'numerical'}, 'BASEMENTAREA_AVG': {'type': 'numerical'}, 'YEARS_BEGINEXPLUATATION_AVG': {'type': 'numerical'}, 'YEARS_BUILD_AVG': {'type': 'numerical'}, 'COMMONAREA_AVG': {'type': 'numerical'}, 'ELEVATORS_AVG': {'type': 'numerical'}, 'ENTRANCES_AVG': {'type': 'numerical'}, 'FLOORSMAX_AVG': {'type': 'numerical'}, 'FLOORSMIN_AVG': {'type': 'numerical'}, 'LANDAREA_AVG': {'type': 'numerical'}, 'LIVINGAPARTMENTS_AVG': {'type': 'numerical'}, 'LIVINGAREA_AVG': {'type': 'numerical'}, 'NONLIVINGAPARTMENTS_AVG': {'type': 'numerical'}, 'NONLIVINGAREA_AVG': {'type': 'numerical'}, 'APARTMENTS_MODE': {'type': 'numerical'}, 'BASEMENTAREA_MODE': {'type': 'numerical'}, 'YEARS_BEGINEXPLUATATION_MODE': {'type': 'numerical'}, 'YEARS_BUILD_MODE': {'type': 'numerical'}, 'COMMONAREA_MODE': {'type': 'numerical'}, 'ELEVATORS_MODE': {'type': 'numerical'}, 'ENTRANCES_MODE': {'type': 'numerical'}, 'FLOORSMAX_MODE': {'type': 'numerical'}, 'FLOORSMIN_MODE': {'type': 'numerical'}, 'LANDAREA_MODE': {'type': 'numerical'}, 'LIVINGAPARTMENTS_MODE': {'type': 'numerical'}, 'LIVINGAREA_MODE': {'type': 'numerical'}, 'NONLIVINGAPARTMENTS_MODE': {'type': 'numerical'}, 'NONLIVINGAREA_MODE': {'type': 'numerical'}, 'APARTMENTS_MEDI': {'type': 'numerical'}, 'BASEMENTAREA_MEDI': {'type': 'numerical'}, 'YEARS_BEGINEXPLUATATION_MEDI': {'type': 'numerical'}, 'YEARS_BUILD_MEDI': {'type': 'numerical'}, 'COMMONAREA_MEDI': {'type': 'numerical'}, 'ELEVATORS_MEDI': {'type': 'numerical'}, 'ENTRANCES_MEDI': {'type': 'numerical'}, 'FLOORSMAX_MEDI': {'type': 'numerical'}, 'FLOORSMIN_MEDI': {'type': 'numerical'}, 'LANDAREA_MEDI': {'type': 'numerical'}, 'LIVINGAPARTMENTS_MEDI': {'type': 'numerical'}, 'LIVINGAREA_MEDI': {'type': 'numerical'}, 'NONLIVINGAPARTMENTS_MEDI': {'type': 'numerical'}, 'NONLIVINGAREA_MEDI': {'type': 'numerical'}, 'FONDKAPREMONT_MODE': {'type': 'categorical'}, 'HOUSETYPE_MODE': {'type': 'categorical'}, 'TOTALAREA_MODE': {'type': 'numerical'}, 'WALLSMATERIAL_MODE': {'type': 'categorical'}, 'EMERGENCYSTATE_MODE': {'type': 'categorical'}, 'OBS_30_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'DEF_30_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'OBS_60_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'DEF_60_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'DAYS_LAST_PHONE_CHANGE': {'type': 'numerical'}, 'FLAG_DOCUMENT_2': {'type': 'categorical'}, 'FLAG_DOCUMENT_3': {'type': 'categorical'}, 'FLAG_DOCUMENT_4': {'type': 'categorical'}, 'FLAG_DOCUMENT_5': {'type': 'categorical'}, 'FLAG_DOCUMENT_6': {'type': 'categorical'}, 'FLAG_DOCUMENT_7': {'type': 'categorical'}, 'FLAG_DOCUMENT_8': {'type': 'categorical'}, 'FLAG_DOCUMENT_9': {'type': 'categorical'}, 'FLAG_DOCUMENT_10': {'type': 'categorical'}, 'FLAG_DOCUMENT_11': {'type': 'categorical'}, 'FLAG_DOCUMENT_12': {'type': 'categorical'}, 'FLAG_DOCUMENT_13': {'type': 'categorical'}, 'FLAG_DOCUMENT_14': {'type': 'categorical'}, 'FLAG_DOCUMENT_15': {'type': 'categorical'}, 'FLAG_DOCUMENT_16': {'type': 'categorical'}, 'FLAG_DOCUMENT_17': {'type': 'categorical'}, 'FLAG_DOCUMENT_18': {'type': 'categorical'}, 'FLAG_DOCUMENT_19': {'type': 'categorical'}, 'FLAG_DOCUMENT_20': {'type': 'categorical'}, 'FLAG_DOCUMENT_21': {'type': 'categorical'}, 'AMT_REQ_CREDIT_BUREAU_HOUR': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_DAY': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_WEEK': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_MON': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_QRT': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_YEAR': {'type': 'numerical'}}, 'bureau': {'SK_BUREAU_ID': {'type': 'categorical'}, 'CREDIT_ACTIVE': {'type': 'categorical'}, 'CREDIT_CURRENCY': {'type': 'categorical'}, 'DAYS_CREDIT': {'type': 'numerical'}, 'CREDIT_DAY_OVERDUE': {'type': 'numerical'}, 'DAYS_CREDIT_ENDDATE': {'type': 'numerical'}, 'DAYS_ENDDATE_FACT': {'type': 'numerical'}, 'AMT_CREDIT_MAX_OVERDUE': {'type': 'numerical'}, 'CNT_CREDIT_PROLONG': {'type': 'numerical'}, 'AMT_CREDIT_SUM': {'type': 'numerical'}, 'AMT_CREDIT_SUM_DEBT': {'type': 'numerical'}, 'AMT_CREDIT_SUM_LIMIT': {'type': 'numerical'}, 'AMT_CREDIT_SUM_OVERDUE': {'type': 'numerical'}, 'CREDIT_TYPE': {'type': 'categorical'}, 'DAYS_CREDIT_UPDATE': {'type': 'numerical'}}, 'bureau_balance': {'MONTHS_BALANCE': {'type': 'numerical'}, 'STATUS': {'type': 'categorical'}}, 'previous_application': {'SK_ID_CURR': {'type': 'categorical'}, 'SK_ID_PREV': {'type': 'categorical'}, 'NAME_CONTRACT_TYPE': {'type': 'categorical'}, 'AMT_ANNUITY': {'type': 'numerical'}, 'AMT_APPLICATION': {'type': 'numerical'}, 'AMT_CREDIT': {'type': 'numerical'}, 'AMT_DOWN_PAYMENT': {'type': 'numerical'}, 'AMT_GOODS_PRICE': {'type': 'numerical'}, 'WEEKDAY_APPR_PROCESS_START': {'type': 'categorical'}, 'HOUR_APPR_PROCESS_START': {'type': 'categorical'}, 'FLAG_LAST_APPL_PER_CONTRACT': {'type': 'categorical'}, 'NFLAG_LAST_APPL_IN_DAY': {'type': 'categorical'}, 'RATE_DOWN_PAYMENT': {'type': 'numerical'}, 'RATE_INTEREST_PRIMARY': {'type': 'numerical'}, 'RATE_INTEREST_PRIVILEGED': {'type': 'numerical'}, 'NAME_CASH_LOAN_PURPOSE': {'type': 'categorical'}, 'NAME_CONTRACT_STATUS': {'type': 'categorical'}, 'DAYS_DECISION': {'type': 'numerical'}, 'NAME_PAYMENT_TYPE': {'type': 'categorical'}, 'CODE_REJECT_REASON': {'type': 'categorical'}, 'NAME_TYPE_SUITE': {'type': 'categorical'}, 'NAME_CLIENT_TYPE': {'type': 'categorical'}, 'NAME_GOODS_CATEGORY': {'type': 'categorical'}, 'NAME_PORTFOLIO': {'type': 'categorical'}, 'NAME_PRODUCT_TYPE': {'type': 'categorical'}, 'CHANNEL_TYPE': {'type': 'categorical'}, 'SELLERPLACE_AREA': {'type': 'numerical'}, 'NAME_SELLER_INDUSTRY': {'type': 'categorical'}, 'CNT_PAYMENT': {'type': 'numerical'}, 'NAME_YIELD_GROUP': {'type': 'categorical'}, 'PRODUCT_COMBINATION': {'type': 'categorical'}, 'DAYS_FIRST_DRAWING': {'type': 'numerical'}, 'DAYS_FIRST_DUE': {'type': 'numerical'}, 'DAYS_LAST_DUE_1ST_VERSION': {'type': 'numerical'}, 'DAYS_LAST_DUE': {'type': 'numerical'}, 'DAYS_TERMINATION': {'type': 'numerical'}, 'NFLAG_INSURED_ON_APPROVAL': {'type': 'categorical'}}, 'POS_CASH_balance': {'SK_ID_PREV': {'type': 'categorical'}, 'MONTHS_BALANCE': {'type': 'numerical'}, 'CNT_INSTALMENT': {'type': 'numerical'}, 'CNT_INSTALMENT_FUTURE': {'type': 'numerical'}, 'NAME_CONTRACT_STATUS': {'type': 'categorical'}, 'SK_DPD': {'type': 'numerical'}, 'SK_DPD_DEF': {'type': 'numerical'}}, 'installments_payments': {'SK_ID_PREV': {'type': 'categorical'}, 'NUM_INSTALMENT_VERSION': {'type': 'numerical'}, 'NUM_INSTALMENT_NUMBER': {'type': 'numerical'}, 'DAYS_INSTALMENT': {'type': 'numerical'}, 'DAYS_ENTRY_PAYMENT': {'type': 'numerical'}, 'AMT_INSTALMENT': {'type': 'numerical'}, 'AMT_PAYMENT': {'type': 'numerical'}}, 'credit_card_balance': {'SK_ID_PREV': {'type': 'categorical'}, 'MONTHS_BALANCE': {'type': 'numerical'}, 'AMT_BALANCE': {'type': 'numerical'}, 'AMT_CREDIT_LIMIT_ACTUAL': {'type': 'numerical'}, 'AMT_DRAWINGS_ATM_CURRENT': {'type': 'numerical'}, 'AMT_DRAWINGS_CURRENT': {'type': 'numerical'}, 'AMT_DRAWINGS_OTHER_CURRENT': {'type': 'numerical'}, 'AMT_DRAWINGS_POS_CURRENT': {'type': 'numerical'}, 'AMT_INST_MIN_REGULARITY': {'type': 'numerical'}, 'AMT_PAYMENT_CURRENT': {'type': 'numerical'}, 'AMT_PAYMENT_TOTAL_CURRENT': {'type': 'numerical'}, 'AMT_RECEIVABLE_PRINCIPAL': {'type': 'numerical'}, 'AMT_RECIVABLE': {'type': 'numerical'}, 'AMT_TOTAL_RECEIVABLE': {'type': 'numerical'}, 'CNT_DRAWINGS_ATM_CURRENT': {'type': 'numerical'}, 'CNT_DRAWINGS_CURRENT': {'type': 'numerical'}, 'CNT_DRAWINGS_OTHER_CURRENT': {'type': 'numerical'}, 'CNT_DRAWINGS_POS_CURRENT': {'type': 'numerical'}, 'CNT_INSTALMENT_MATURE_CUM': {'type': 'numerical'}, 'NAME_CONTRACT_STATUS': {'type': 'categorical'}, 'SK_DPD': {'type': 'numerical'}, 'SK_DPD_DEF': {'type': 'numerical'}}}

In [14]:

def eda_per_table_persisting_result_html(df: pd.DataFrame, schema,table_name, target_aware: bool):
    results= eda_per_table(df,schema,table_name,target_aware)
    with open("eda_report.html", "w", encoding="utf-8") as f:
            f.write("<html><body>")
            for key,value in results.items() :
                  f.write(f"<h2>{key}</h2>")
                  f.write("<pre>")
                  for inside_keys,data_frames in value.items():
                        f.write(f"<h3>{inside_keys}</h3>")
                        f.write("</pre>")
                        f.write(data_frames.to_html(index=False))
                        f.write("</pre>")
            f.write("</body></html>")



def eda_per_table_printing_results(df: pd.DataFrame,schema: dict, table_name: str, target_aware: bool):
    results=eda_per_table(df,schema,table_name,target_aware)
    for key,values in results.items() :
        print("--------------------------------------")
        print(key)
        print_dataframes(values)


def print_dataframes(dicts):
    for key,a_dataframe in dicts.items():
        print(key)
        display(a_dataframe)
    return


def eda_per_table(df: pd.DataFrame,schema: dict,table_name, target_aware: bool) -> dict :
    results={}
    for col in df.columns:
        dict_of_dataframes,column_name= eda_per_column(df,schema,table_name,col,target_aware)
        results[column_name]=dict_of_dataframes
    return results


def eda_per_column(df: pd.DataFrame,schema: dict,table_name,column_name, target_aware: bool):
    dict_of_dataframes={}
    if(is_categorical(schema,table_name,column_name)):
        dict_of_dataframes= basic_eda_per_column_categorical(df,column_name, target_aware)
    else:
        dict_of_dataframes=basic_eda_per_column_numerical(df,column_name, target_aware) 
    return dict_of_dataframes,column_name




def is_categorical(schema: dict,table_name,column_name):
    try:
            col_type = schema[table_name][column_name]["type"]
            return col_type == "categorical"
    except KeyError:
        print(f"Warning: '{column_name}' not found in schema for '{table_name}'. Defaulting to categorical.")
        return True


def basic_eda_per_column_numerical(df: pd.DataFrame, column_name, target_aware: bool) -> dict: 
    column=df[column_name]
    dict_to_return={}
    basic_data_dict={}

    mean=column.mean()
    median=column.median()
    standar_deviation=column.std()

    basic_data_dict["min"]=column.min()
    basic_data_dict["max"]=column.max()
    basic_data_dict["mean"]=mean

    basic_data_dict["trim_mean"]= trim_mean(column.dropna(),proportiontocut=0.1)
    basic_data_dict["median"]= median
    basic_data_dict["standard_deviation"]=standar_deviation
    basic_data_dict["standard_error"]=column.sem()
    if(mean != 0):
        basic_data_dict["coefficient_of_variation"]= standar_deviation / abs(mean)

    basic_data_dataframe=pd.DataFrame([basic_data_dict])
    distribution_metrics_dataframe=pd.DataFrame([get_distribution_metrics(df,column_name)])

    dict_to_return["basic_data"]=basic_data_dataframe

    if(column.isnull().sum() > 0):
        nulls_metrics_dataframe=pd.DataFrame([get_null_info(df,column_name,target_aware)])
        dict_to_return["missings_metrics"]=nulls_metrics_dataframe

    dict_to_return["distribution_metrics"]=distribution_metrics_dataframe

    return dict_to_return


def get_null_info(df: pd.DataFrame, column_name, target_aware: bool) -> dict:
    nulls_info={}
    
    column=df[column_name]

    column_null_maks=column.isnull()
    null_total=column_null_maks.sum()
    null_porcentaje= column_null_maks.mean() * 100
    rows_with_null=df[column_null_maks]


    non_null_maks=~column.isnull()
    non_null_total=non_null_maks.sum()
    non_null_porcentaje=non_null_maks.mean() * 100
    non_null_values=df[non_null_maks]



    nulls_info["nulls_amount"]=null_total
    nulls_info["nulls_porcentaje"]=null_porcentaje

    nulls_info["non_null_amount"] = non_null_total
    nulls_info["non_null_porcentaje"] = non_null_porcentaje

    if(target_aware):
        target_correlation_nulls=rows_with_null["TARGET"].mean() * 100
        nulls_info["default_ratio_nulls"]=target_correlation_nulls

        default_ratio_non_null= non_null_values["TARGET"].mean() * 100
        nulls_info["non_null_default_ratio"] = default_ratio_non_null
    


    return nulls_info





def get_distribution_metrics(df: pd.DataFrame, column_name) -> dict:
    distribution_dict={}
    column=df[column_name]

    median= column.median()
    percentil_99=column.quantile(0.99)
    percentil_90=column.quantile(0.90)

    distribution_dict["skew"]=column.skew()
    distribution_dict["p90"]=percentil_90
    distribution_dict["p99"]=percentil_99

    if(median != 0):
        distribution_dict["ratio_p99_p50"]= percentil_99 / median
    if(percentil_90 !=0):
        distribution_dict["ratio_p99_p90"]= percentil_99 / percentil_90

    return distribution_dict
    

def basic_eda_per_column_categorical(df: pd.DataFrame,column_name, target_aware: bool) -> dict: 
    column=df[column_name]
    basic_data_dict={}
    cardinality=column.nunique(dropna=False)
    basic_data_dict["cardinality"]=cardinality
    basic_data_dict["mode"]=column.mode().to_list()
    dict_to_return={}
    dict_to_return["basic_data"]=pd.DataFrame([basic_data_dict])
    if(30 > cardinality and target_aware):
        default_rate_per_category=(df.groupby(column_name,dropna=False)["TARGET"].mean() *100).reset_index(name="TARGET_RATE") 
        dict_to_return["default_rate"]=default_rate_per_category
    dict_to_return["frequency"]=get_counts_per_class(column)
    return dict_to_return


def get_counts_per_class(column : pd.Series):
    value_count_serie=column.value_counts(dropna=False)
    cardinality=value_count_serie.shape[0]
    if(cardinality < 1000):
        result_df= value_count_serie.reset_index()
        result_df.columns= ["CATEGORY", "COUNT"]
        result_df["SEGMENT"] = "full"
        return result_df
    head_df= value_count_serie.head(20).reset_index()
    head_df.columns= ["CATEGORY", "COUNT"]
    head_df["SEGMENT"] = "top"
    tail_df= value_count_serie.tail(20).reset_index()
    tail_df.columns= ["CATEGORY", "COUNT"]
    tail_df["SEGMENT"] = "bottom"
    resume_df=pd.concat([head_df,tail_df],ignore_index=True)
    return resume_df

In [24]:
eda_per_column(df,schema,"application","CODE_GENDER")

({'basic_data':    cardinality mode
  0            3  [F],
  'default_rate':   CODE_GENDER  TARGET_RATE
  0           F     6.999328
  1           M    10.141920
  2         XNA     0.000000,
  'frequency':   CATEGORY   COUNT SEGMENT
  0        F  202448    full
  1        M  105059    full
  2      XNA       4    full},
 'CODE_GENDER')

In [15]:
df_previous_aplications=pd.read_csv("../data/previous_application.csv")
df_previous_aplications.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
eda_per_table_persisting_result_html(df,schema,"application",True)

In [16]:
eda_per_table_printing_results(df_previous_aplications,schema,"previous_application",False)

--------------------------------------
SK_ID_PREV
basic_data

   cardinality                                               mode
0      1670214  [1000001, 1000002, 1000003, 1000004, 1000005, ...

frequency

    CATEGORY  COUNT SEGMENT
0    2030495      1     top
1    1035848      1     top
2    1526498      1     top
3    2148893      1     top
4    2437429      1     top
5    1624541      1     top
6    2095602      1     top
7    1203077      1     top
8    2842426      1     top
9    1758596      1     top
10   2123441      1     top
11   1576917      1     top
12   2780405      1     top
13   1343601      1     top
14   1224660      1     top
15   1006647      1     top
16   2206965      1     top
17   2123813      1     top
18   1825172      1     top
19   1453218      1     top
20   1404368      1  bottom
21   1913170      1  bottom
22   1992503      1  bottom
23   2515722      1  bottom
24   2092875      1  bottom
25   2512450      1  bottom
26   1449280      1  bottom
27   2749815      1  bottom
28   1964255      1  bottom
29   1320749      1  bottom
30   1163658      1  bottom
31   2453071      1  bottom
32   1789338      1  bottom
33   2040003      1  bottom
34   2457356      1  bottom
35   2811649      1  bottom
36   1221292      1  bottom
37   2780117      1  bottom
38   2194001      1  bottom
39   2418762      1  bottom

--------------------------------------
SK_ID_CURR
basic_data

   cardinality      mode
0       338857  [187868]

frequency

    CATEGORY  COUNT SEGMENT
0     187868     77     top
1     265681     73     top
2     173680     72     top
3     242412     68     top
4     206783     67     top
5     156367     66     top
6     389950     64     top
7     382179     64     top
8     198355     63     top
9     345161     62     top
10    446486     62     top
11    238250     61     top
12    280586     61     top
13    133023     60     top
14    227585     60     top
15    206862     60     top
16    242431     59     top
17    401563     59     top
18    110899     58     top
19    235163     58     top
20    206911      1  bottom
21    209221      1  bottom
22    105394      1  bottom
23    437028      1  bottom
24    283899      1  bottom
25    306897      1  bottom
26    345033      1  bottom
27    425318      1  bottom
28    374091      1  bottom
29    272268      1  bottom
30    185365      1  bottom
31    447204      1  bottom
32    403732      1  bottom
33    290883      1  bottom
34    340334      1  bottom
35    135285      1  bottom
36    311960      1  bottom
37    427136      1  bottom
38    241434      1  bottom
39    191629      1  bottom

--------------------------------------
NAME_CONTRACT_TYPE
basic_data

   cardinality          mode
0            4  [Cash loans]

frequency

          CATEGORY   COUNT SEGMENT
0       Cash loans  747553    full
1   Consumer loans  729151    full
2  Revolving loans  193164    full
3              XNA     346    full

--------------------------------------
AMT_ANNUITY
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,418058.145,15955.120659,13297.603016,11250.0,14782.137335,12.974881,0.926482

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        372235         22.286665          1297979            77.713335

distribution_metrics

       skew       p90         p99  ratio_p99_p50  ratio_p99_p90
0  2.692572  34703.82  69685.7886       6.194292       2.008015

--------------------------------------
AMT_APPLICATION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,6905160.0,175233.86036,106380.23792,71046.0,292779.762386,226.545267,1.670794

distribution_metrics

       skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  3.391442  450000.0  1350000.0      19.001773            3.0

--------------------------------------
AMT_CREDIT
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,6905160.0,196114.021218,121456.838435,80541.0,318574.616547,246.50472,1.624436

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0             1           0.00006          1670213             99.99994

distribution_metrics

       skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  3.245815  533160.0  1515377.7      18.814985       2.842257

--------------------------------------
AMT_DOWN_PAYMENT
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-0.9,3060045.0,6697.402139,3518.712186,1638.0,20921.49541,23.774887,3.123822

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        895844          53.63648           774370             46.36352

distribution_metrics

        skew      p90        p99  ratio_p99_p50  ratio_p99_p90
0  36.476576  17109.0  65930.895      40.250852        3.85358

--------------------------------------
AMT_GOODS_PRICE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,6905160.0,227847.279283,154602.492437,112320.0,315396.557937,278.263508,1.384245

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        385515         23.081773          1284699            76.918227

distribution_metrics

      skew       p90        p99  ratio_p99_p50  ratio_p99_p90
0  3.07369  585000.0  1395000.0      12.419872       2.384615

--------------------------------------
WEEKDAY_APPR_PROCESS_START
basic_data

   cardinality       mode
0            7  [TUESDAY]

frequency

    CATEGORY   COUNT SEGMENT
0    TUESDAY  255118    full
1  WEDNESDAY  255010    full
2     MONDAY  253557    full
3     FRIDAY  252048    full
4   THURSDAY  249099    full
5   SATURDAY  240631    full
6     SUNDAY  164751    full

--------------------------------------
HOUR_APPR_PROCESS_START
basic_data

   cardinality  mode
0           24  [11]

frequency

    CATEGORY   COUNT SEGMENT
0         11  192728    full
1         12  185980    full
2         10  181690    full
3         13  172256    full
4         14  157711    full
5         15  142965    full
6          9  127002    full
7         16  121361    full
8         17   95064    full
9          8   73085    full
10        18   64156    full
11         7   45646    full
12        19   34089    full
13         6   25759    full
14         5   15392    full
15        20   14535    full
16         4    9319    full
17         3    5035    full
18        21    4082    full
19         2    1116    full
20        22     720    full
21         1     212    full
22        23     202    full
23         0     109    full

--------------------------------------
FLAG_LAST_APPL_PER_CONTRACT
basic_data

   cardinality mode
0            2  [Y]

frequency

  CATEGORY    COUNT SEGMENT
0        Y  1661739    full
1        N     8475    full

--------------------------------------
NFLAG_LAST_APPL_IN_DAY
basic_data

   cardinality mode
0            2  [1]

frequency

   CATEGORY    COUNT SEGMENT
0         1  1664314    full
1         0     5900    full

--------------------------------------
RATE_DOWN_PAYMENT
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-0.000015,1.0,0.079637,0.058818,0.051605,0.107823,0.000123,1.353938

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        895844          53.63648           774370             46.36352

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  2.107713  0.211997  0.521085      10.097545       2.457987

--------------------------------------
RATE_INTEREST_PRIMARY
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.034781,1.0,0.188357,0.177329,0.189122,0.087671,0.001136,0.465452

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0       1664263         99.643698             5951             0.356302

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  5.198204  0.1969  0.696178         3.6811       3.535689

--------------------------------------
RATE_INTEREST_PRIVILEGED
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.37315,1.0,0.773503,0.784966,0.835095,0.100879,0.001308,0.130418

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0       1664263         99.643698             5951             0.356302

distribution_metrics

      skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -1.00768  0.867336  0.867336       1.038608            1.0

--------------------------------------
NAME_CASH_LOAN_PURPOSE
basic_data

   cardinality   mode
0           25  [XAP]

frequency

                            CATEGORY   COUNT SEGMENT
0                                XAP  922661    full
1                                XNA  677918    full
2                            Repairs   23765    full
3                              Other   15608    full
4                       Urgent needs    8412    full
5                  Buying a used car    2888    full
6       Building a house or an annex    2693    full
7                  Everyday expenses    2416    full
8                           Medicine    2174    full
9            Payments on other loans    1931    full
10                         Education    1573    full
11                           Journey    1239    full
12  Purchase of electronic equipment    1061    full
13                  Buying a new car    1012    full
14          Wedding / gift / holiday     962    full
15                     Buying a home     865    full
16                       Car repairs     797    full
17                         Furniture     749    full
18      Buying a holiday home / land     533    full
19              Business development     426    full
20       Gasification / water supply     300    full
21                   Buying a garage     136    full
22                             Hobby      55    full
23          Money for a third person      25    full
24          Refusal to name the goal      15    full

--------------------------------------
NAME_CONTRACT_STATUS
basic_data

   cardinality        mode
0            4  [Approved]

frequency

       CATEGORY    COUNT SEGMENT
0      Approved  1036781    full
1      Canceled   316319    full
2       Refused   290678    full
3  Unused offer    26436    full

--------------------------------------
DAYS_DECISION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2922,-1,-880.679668,-769.918487,-581.0,779.099667,0.602847,0.884657

distribution_metrics

      skew    p90   p99  ratio_p99_p50  ratio_p99_p90
0 -1.05308 -152.0 -14.0       0.024096       0.092105

--------------------------------------
NAME_PAYMENT_TYPE
basic_data

   cardinality                     mode
0            4  [Cash through the bank]

frequency

                                    CATEGORY    COUNT SEGMENT
0                      Cash through the bank  1033552    full
1                                        XNA   627384    full
2                 Non-cash from your account     8193    full
3  Cashless from the account of the employer     1085    full

--------------------------------------
CODE_REJECT_REASON
basic_data

   cardinality   mode
0            9  [XAP]

frequency

  CATEGORY    COUNT SEGMENT
0      XAP  1353093    full
1       HC   175231    full
2    LIMIT    55680    full
3      SCO    37467    full
4   CLIENT    26436    full
5    SCOFR    12811    full
6      XNA     5244    full
7    VERIF     3535    full
8   SYSTEM      717    full

--------------------------------------
NAME_TYPE_SUITE
basic_data

   cardinality             mode
0            8  [Unaccompanied]

frequency

          CATEGORY   COUNT SEGMENT
0              NaN  820405    full
1    Unaccompanied  508970    full
2           Family  213263    full
3  Spouse, partner   67069    full
4         Children   31566    full
5          Other_B   17624    full
6          Other_A    9077    full
7  Group of people    2240    full

--------------------------------------
NAME_CLIENT_TYPE
basic_data

   cardinality        mode
0            4  [Repeater]

frequency

    CATEGORY    COUNT SEGMENT
0   Repeater  1231261    full
1        New   301363    full
2  Refreshed   135649    full
3        XNA     1941    full

--------------------------------------
NAME_GOODS_CATEGORY
basic_data

   cardinality   mode
0           28  [XNA]

frequency

                    CATEGORY   COUNT SEGMENT
0                        XNA  950809    full
1                     Mobile  224708    full
2       Consumer Electronics  121576    full
3                  Computers  105769    full
4                Audio/Video   99441    full
5                  Furniture   53656    full
6   Photo / Cinema Equipment   25021    full
7     Construction Materials   24995    full
8   Clothing and Accessories   23554    full
9           Auto Accessories    7381    full
10                   Jewelry    6290    full
11                 Homewares    5023    full
12          Medical Supplies    3843    full
13                  Vehicles    3370    full
14         Sport and Leisure    2981    full
15                 Gardening    2668    full
16                     Other    2554    full
17         Office Appliances    2333    full
18                   Tourism    1659    full
19                  Medicine    1550    full
20              Direct Sales     446    full
21                   Fitness     209    full
22        Additional Service     128    full
23                 Education     107    full
24                    Weapon      77    full
25                 Insurance      64    full
26                   Animals       1    full
27        House Construction       1    full

--------------------------------------
NAME_PORTFOLIO
basic_data

   cardinality   mode
0            5  [POS]

frequency

  CATEGORY   COUNT SEGMENT
0      POS  691011    full
1     Cash  461563    full
2      XNA  372230    full
3    Cards  144985    full
4     Cars     425    full

--------------------------------------
NAME_PRODUCT_TYPE
basic_data

   cardinality   mode
0            3  [XNA]

frequency

  CATEGORY    COUNT SEGMENT
0      XNA  1063666    full
1   x-sell   456287    full
2  walk-in   150261    full

--------------------------------------
CHANNEL_TYPE
basic_data

   cardinality                       mode
0            8  [Credit and cash offices]

frequency

                     CATEGORY   COUNT SEGMENT
0     Credit and cash offices  719968    full
1                Country-wide  494690    full
2                       Stone  212083    full
3            Regional / Local  108528    full
4              Contact center   71297    full
5             AP+ (Cash loan)   57046    full
6  Channel of corporate sales    6150    full
7                  Car dealer     452    full

--------------------------------------
SELLERPLACE_AREA
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-1,4000000,313.951115,59.660309,3.0,7127.443459,5.515028,22.702399

distribution_metrics

         skew    p90     p99  ratio_p99_p50  ratio_p99_p90
0  529.620279  919.0  3570.0         1190.0       3.884657

--------------------------------------
NAME_SELLER_INDUSTRY
basic_data

   cardinality   mode
0           11  [XNA]

frequency

                CATEGORY   COUNT SEGMENT
0                    XNA  855720    full
1   Consumer electronics  398265    full
2           Connectivity  276029    full
3              Furniture   57849    full
4           Construction   29781    full
5               Clothing   23949    full
6               Industry   19194    full
7        Auto technology    4990    full
8                Jewelry    2709    full
9           MLM partners    1215    full
10               Tourism     513    full

--------------------------------------
CNT_PAYMENT
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,84.0,16.054082,13.696841,12.0,14.567288,0.012786,0.907388

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        372230         22.286366          1297984            77.713634

distribution_metrics

       skew   p90   p99  ratio_p99_p50  ratio_p99_p90
0  1.531403  36.0  60.0            5.0       1.666667

--------------------------------------
NAME_YIELD_GROUP
basic_data

   cardinality   mode
0            5  [XNA]

frequency

     CATEGORY   COUNT SEGMENT
0         XNA  517215    full
1      middle  385532    full
2        high  353331    full
3  low_normal  322095    full
4  low_action   92041    full

--------------------------------------
PRODUCT_COMBINATION
basic_data

   cardinality    mode
0           18  [Cash]

frequency

                          CATEGORY   COUNT SEGMENT
0                             Cash  285990    full
1      POS household with interest  263622    full
2         POS mobile with interest  220670    full
3              Cash X-Sell: middle  143883    full
4                 Cash X-Sell: low  130248    full
5                      Card Street  112582    full
6       POS industry with interest   98833    full
7   POS household without interest   82908    full
8                      Card X-Sell   80582    full
9                Cash Street: high   59639    full
10               Cash X-Sell: high   59301    full
11             Cash Street: middle   34658    full
12                Cash Street: low   33834    full
13     POS mobile without interest   24082    full
14         POS other with interest   23879    full
15   POS industry without interest   12602    full
16     POS others without interest    2555    full
17                             NaN     346    full

--------------------------------------
DAYS_FIRST_DRAWING
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2922.0,365243.0,342209.855039,365243.0,365243.0,88916.115833,89.043137,0.259829

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        673065         40.298129           997149            59.701871

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -3.601343  365243.0  365243.0            1.0            1.0

--------------------------------------
DAYS_FIRST_DUE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2892.0,365243.0,13826.269337,-991.720355,-831.0,72444.869708,72.548361,5.239654

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        673065         40.298129           997149            59.701871

distribution_metrics

       skew    p90       p99  ratio_p99_p50  ratio_p99_p90
0  4.644096 -173.0  365243.0    -439.522262   -2111.231214

--------------------------------------
DAYS_LAST_DUE_1ST_VERSION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2801.0,365243.0,33767.774054,-485.4279,-361.0,106857.034789,107.009686,3.164468

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        673065         40.298129           997149            59.701871

distribution_metrics

      skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  2.77945  1432.0  365243.0   -1011.753463     255.057961

--------------------------------------
DAYS_LAST_DUE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2889.0,365243.0,76582.403064,50368.696089,-537.0,149647.415123,149.861195,1.954071

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        673065         40.298129           997149            59.701871

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  1.410473  365243.0  365243.0    -680.154562            1.0

--------------------------------------
DAYS_TERMINATION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-2874.0,365243.0,81992.343838,57128.270429,-499.0,153303.516729,153.522519,1.86973

missings_metrics

   nulls_amount  nulls_porcentaje  non_null_amount  non_null_porcentaje
0        673065         40.298129           997149            59.701871

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  1.306376  365243.0  365243.0      -731.9499            1.0

--------------------------------------
NFLAG_INSURED_ON_APPROVAL
basic_data

   cardinality   mode
0            3  [0.0]

frequency

   CATEGORY   COUNT SEGMENT
0       NaN  673065    full
1       0.0  665527    full
2       1.0  331622    full

In [ ]:
create_files_nulls_per_colmun(df,"aplication_train")

print(len(df))

In [ ]:

#now we will explore the hypothesis of train one model per type of contract. Starting for how viable is with the data available

print(df["NAME_CONTRACT_TYPE"].value_counts(normalize=True) * 100)
print(df.groupby("NAME_CONTRACT_TYPE")["TARGET"].mean() * 100)

#Considering the volume of the minoritary class (less than 10%) and their event ratio (5%) seems not ideal have to separate the models.

In [31]:
len(df[ 0 < df["DAYS_ID_PUBLISH"]] )

0

In [ ]:
#here i want to check if the main variables that describes the loan change their distribution and trending between the type of contract,
#and also see how much change in the case of default. 

df["LOG_AMT_CREDIT"]= np.log10(df["AMT_CREDIT"])

g = sns.displot(
    data=df,
    x="LOG_AMT_CREDIT",
    hue="NAME_CONTRACT_TYPE",
    bins=50,
    element="step",
    stat="density",
    col="TARGET",
    common_norm=False
)

for ax in g.axes.flat:
    ax.ticklabel_format(style='plain', axis='x')
    ax.ticklabel_format(style='plain', axis='y')

#default and the mont of the loan have negative correlation. In both type of contracts. That's a good proof about the similar behaivor between clases 
#and seems unnecesary split and train 2 diferent models.

In [ ]:
bins= np.arange(0,df["AMT_CREDIT"].max() + 100000, 100000)
df["BINED_AMT_CREDIT"]=  pd.qcut(df["AMT_CREDIT"],10)
df_groupBy_bins = df.groupby(["BINED_AMT_CREDIT","NAME_CONTRACT_TYPE"],observed=True)["TARGET"].agg(
    DEFAULT_RATE="mean",
    COUNT="size").reset_index()
df_groupBy_bins["CREDIT_BIN_CENTER"] = df_groupBy_bins["BINED_AMT_CREDIT"].apply(lambda x: x.mid)


gr=sns.relplot(data=df_groupBy_bins,x="CREDIT_BIN_CENTER",y="DEFAULT_RATE",kind="line",col="NAME_CONTRACT_TYPE")

In [ ]:
sns.scatterplot(
    data=df_groupBy_bins,
    x="CREDIT_BIN_CENTER",
    y="DEFAULT_RATE",
    hue="NAME_CONTRACT_TYPE",
    size="COUNT"
)

In [ ]:
"""About the idea of creating 2 different models for each type of contract: 

The amount of data and events is something to consider.
revolving loans represent 9.5% of observations and have a default ratio of 5%.
Therefore, train separate models significantly reduce the amount of total data and default events.

the analysis of the deciles of amount of credit and their respective default rate show similar overall trends for both contracts types, but have noticiable diferences in some segments.
For linear models this would require some features to model the interaction but in case of using tree based models the feature CONTRACT_TYPE 
seems enough

In conclusion, this preliminary analisis show there is no strong evidence supporting the need for two separate models. Even so, this hypothesis
will be tested formally later comparing model performance.
"""

In [ ]:
bureau_df=pd.read_csv("../data/bureau.csv")
bureau_df.head()

In [ ]:
create_files_nulls_per_colmun(bureau_df,"bureau")

In [ ]:
create_files_nulls_per_colmun(previous,"previous_aplication")